---
title: "W_UP_01"
author: "David Montes"
date: "Spring 2026"
output: html_document
---



The report structure should include five sections.  see below



```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
mydata <- read.csv(file="pushups.csv")
```

# Introduction 
the research question is who does more pushups in two minutes- players on line or skilled position player.
data came from georgetown college varsity football team.
data are number of pushups done in two minutes and that is numerical continuouse and position which is a categorical variable.

Create an Rstudio project in your shared space on rstudio.cloud.  Using the dataset called pushups from the tigerstats package in R; answer the question posed by this null and alternate hypothesis in an html markdown document.

$H_0$: There is no difference between the average number of pushups done in two minutes between skill and line players

$H_A$: The average number of pushups done by line players is statistically different than that of skill players.

# Methods

<!--Decide on your methods: use "variable analysis" or other appropriate descriptors. Make sure to choose at least one graphical method and at least one numerical method.!-->

# Results

<!--Divide this section into two sub-sections: One for your descriptive results and one for your inferential results.!-->

## Descriptive Results
data are from geortown varsity football team

data are number of pushups done in 2 minnutes (numerical, continuous) position which is catagorical variable.

response variable is number of pushups done in 2 mins explanatory variable is position
NUM-CAT 
so we need boxplot

read the data

### Graphical Descriptive Results

<!--Graphical results here. Make sure to show your code. Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too. Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

## Inferential Results

<!--State hypothesis clearly. Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc. Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here. If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason. Watch the chapter 6 videos from the GeorgeTown videos collection.!-->

